name: CI
on:
  push:
    branches:
    - debug-ci

jobs:

  update-docker-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
    - run: scripts/update-docker-images.sh
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  update-website:
    needs: [update-docker-images]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
        apps: cs
    - run: |
        ./mill docs.generate --npm-install --yarn-run-build
        scripts/website/versioned-docs.sh --update
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WEBSITE_DIR: docs/website
        VERSIONED_DOCS_REPO: almond-sh/versioned-docs
    - run: |
        scripts/website/versioned-docs.sh
        ./mill docs.generate --npm-install --yarn-run-build --relativize
        scripts/website/push-website.sh
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WEBSITE_DIR: docs/website
        REPO: almond-sh/almond
        VERSIONED_DOCS_REPO: almond-sh/versioned-docs
